version: '3.5'

services:
  star-wars:
    container_name: star-wars
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=star-wars
    ports:
      - '1000:8000'
    networks:
      - star-wars-network
    depends_on:
      - star-wars-postgres

  star-wars-postgres:
    container_name: star-wars-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: star-wars_symfony
    volumes:
      - star-wars-postgres-pgsql-data:/var/lib/postgresql/data:rw
    networks:
      - star-wars-network

networks:
  star-wars-network:

volumes:
  star-wars-postgres-pgsql-data:
